# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 21:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe_Social',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('nome', models.CharField(max_length=200)),
                ('preco_atendimento', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('nivel_especialidade', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(3.0)])),
                ('nivel_tecnologia', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(3.0)])),
                ('media_conforto', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(3.0)])),
                ('velocidade_atendimento', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(3.0)])),
            ],
        ),
    ]
