# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classe_social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe_social',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
    ]
