# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo', '0002_auto_20160921_1800'),
        ('medico', '0002_auto_20161118_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('loguin', models.CharField(max_length=10)),
                ('senha', models.CharField(max_length=20)),
                ('caixa', models.FloatField()),
                ('medicos_ativos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico.Medico')),
                ('modulos_ativos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo.Modulo')),
            ],
        ),
    ]
