# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='loguin',
        ),
        migrations.RemoveField(
            model_name='time',
            name='medicos_ativos',
        ),
        migrations.RemoveField(
            model_name='time',
            name='modulos_ativos',
        ),
        migrations.AddField(
            model_name='time',
            name='login',
            field=models.CharField(default='N', max_length=15),
            preserve_default=False,
        ),
    ]
