# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 14:15
from __future__ import unicode_literals

import Time.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time', '0003_auto_20170406_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='login',
            field=models.CharField(max_length=15, validators=[Time.validator.validate_blank]),
        ),
    ]
