# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 12:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='codigo')),
                ('nome', models.CharField(max_length=200)),
                ('custo_de_aquisicao', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('custo_mensal', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('tecnologia', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1)),
                ('conforto', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1)),
                ('capacidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('preco_do_tratamento', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
    ]
