# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0002_auto_20160801_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
        migrations.AlterUniqueTogether(
            name='modulo',
            unique_together=set([('codigo', 'nome')]),
        ),
    ]
