# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-12 17:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classe_social', '0001_initial'),
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area_ClasseSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.Area')),
                ('classe_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classe_social.Classe_Social')),
            ],
        ),
    ]
