# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 14:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0002_area_classesocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area_classesocial',
            name='desvios',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
