# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 15:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0004_auto_20161118_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area_classesocial',
            name='desvios',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
