# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 21:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
            ],
        ),
    ]
