# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-03 19:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0005_auto_20170303_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('entradaA', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('entradaB', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('entradaC', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('entradaD', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('entradaE', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('desvioA', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('desvioB', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('desvioC', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('desvioD', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('desvioE', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.Area')),
            ],
        ),
    ]
