# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-03 19:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0005_auto_20170303_1606'),
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento_ModificaEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modificadorEntrada', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('modificadorDesvio', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('area_classe_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.Area_ClasseSocial')),
            ],
        ),
        migrations.RemoveField(
            model_name='evento',
            name='area',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='desvioA',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='desvioB',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='desvioC',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='desvioD',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='desvioE',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='entradaA',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='entradaB',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='entradaC',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='entradaD',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='entradaE',
        ),
        migrations.AlterField(
            model_name='evento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
        migrations.AddField(
            model_name='evento_modificaentrada',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Evento'),
        ),
    ]
