# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-03 19:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_auto_20170303_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento_modificaentrada',
            name='modificadorDesvio',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='evento_modificaentrada',
            name='modificadorEntrada',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
