# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 15:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroRodada', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('duracao', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('evento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evento.Evento')),
            ],
            options={
                'verbose_name': 'rodada',
                'verbose_name_plural': 'rodadas',
            },
        ),
    ]
